FROM node:20-bullseye-slim

WORKDIR /workspace/legacy-frontend

# 依存関係をインストール
COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN mkdir -p /workspace/legacy-frontend/node_modules && \
  chown -R node:node /workspace && \
  mkdir -p /workspace/legacy-frontend/.pnpm-store && \
  chown -R node:node /workspace/legacy-frontend/.pnpm-store
RUN npm install -g pnpm

USER node

RUN pnpm config set store-dir /workspace/legacy-frontend/.pnpm-store

RUN pnpm install

# Next.jsによってテレメトリデータを収集するのを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

CMD [ "sleep", "infinity" ]