# Generated by Django 4.2.16 on 2024-11-04 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_room', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDistinguished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_distinguished', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TargetStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_students', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('timetable_number', models.CharField(max_length=100)),
                ('numbering', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '第1クオーター'), (2, '第2クオーター'), (3, '第3クオーター'), (4, '第4クオーター')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '日曜日')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period', models.PositiveSmallIntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限'), (6, '6限'), (7, '7限')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('is_intensive', models.BooleanField()),
                ('number_of_proper', models.PositiveSmallIntegerField()),
                ('class_format', models.CharField(max_length=100)),
                ('lectures_form', models.CharField(max_length=100)),
                ('number_of_credit', models.PositiveSmallIntegerField()),
                ('class_to_a_maximum_of_60_redit', models.BooleanField()),
                ('note', models.CharField(max_length=400)),
                ('explanation', models.TextField()),
                ('url', models.URLField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculty')),
                ('instructors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.instructors')),
                ('lecture_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lectureroom')),
                ('subject_distinguished', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subjectdistinguished')),
                ('target_students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.targetstudents')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.PositiveSmallIntegerField()),
                ('first_choice', models.PositiveSmallIntegerField()),
                ('second_choice', models.PositiveSmallIntegerField()),
                ('third_choice', models.PositiveSmallIntegerField()),
                ('fourth_choice', models.PositiveSmallIntegerField()),
                ('fifth_choice', models.PositiveSmallIntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.syllabus')),
            ],
        ),
    ]
