# Generated by Django 4.2.16 on 2024-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courseregistrationadjustmentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='instructors',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructors',
            field=models.ManyToManyField(null=True, to='api.instructors'),
        ),
    ]
