# Generated by Django 4.2.16 on 2024-11-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_semester_weekdayperiod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='weekdat_period',
            new_name='weekday_period',
        ),
    ]
