# Generated by Django 4.2.16 on 2024-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_weekdat_period_syllabus_weekday_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='number_of_proper',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
