# Generated by Django 4.2.16 on 2024-11-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_syllabus_number_of_proper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrationstatus',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
        ),
    ]
