FROM node:20-bullseye-slim

WORKDIR /workspace/frontend

# 依存関係をインストール
COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN mkdir -p /workspace/frontend/node_modules && \
  chown -R node:node /workspace && \
  mkdir -p /workspace/frontend/.pnpm-store && \
  chown -R node:node /workspace/frontend/.pnpm-store
RUN npm install -g pnpm

USER node

RUN pnpm config set store-dir /workspace/frontend/.pnpm-store

RUN pnpm install

# Next.jsによってテレメトリデータを収集するのを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# 注意: ポートのマッピングはdocker-composeで行うため、設定しない
