FROM node:20-bullseye-slim

WORKDIR /workspace

# 依存関係をインストール
COPY --chown=user:node package.json yarn.lock* ./

RUN mkdir -p /workspace/node_modules && chown -R node:node /workspace
RUN npm install -g pnpm

USER node
RUN pnpm install

# Next.jsによってテレメトリデータを収集するのを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# 注意: ポートのマッピングはdocker-composeで行うため、設定しない

CMD ["yarn", "dev"]