FROM node:20-bullseye-slim

WORKDIR /workspace

RUN mkdir -p /workspace/node_modules

# 依存関係をインストール
COPY package.json yarn.lock* ./

RUN yarn install

RUN chown -R node:node ./
USER node

# Next.jsによってテレメトリデータを収集するのを無効にする
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# 注意: ポートのマッピングはdocker-composeで行うため、設定しない

CMD ["yarn", "dev"]