services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: no
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - type: bind
        source: .
        target: /workspace

      - type: volume
        source: frontend-node-modules
        target: /workspace/frontend/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev
    user: "${UID:-1000}:${GID:-1000}"

  web:
    restart: no
    environment:
      - SERVER_NAME=localhost

  mock-page:
    build:
      context: ./mock-page
      dockerfile: Dockerfile.dev
    ports:
      - 1313:1313
    networks:
      - rishu-app_network

  legacy-frontend:
    build:
      context: ./legacy-frontend
      dockerfile: Dockerfile.dev
    restart: no
    ports:
      - 3001:3000
    volumes:
      - type: bind
        source: .
        target: /workspace

      - type: volume
        source: legacy-frontend-node-modules
        target: /workspace/legacy-frontend/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev
    user: "${UID:-1000}:${GID:-1000}"

  legacy-syllabus-frontend:
    build:
      context: ./legacy-syllabus-frontend
      dockerfile: Dockerfile.dev
    restart: no
    depends_on:
      - syllabus-backend
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: legacy-syllabus-frontend-node-modules
        target: /workspace/legacy-syllabus-frontend/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - rishu-app_network
    command: pnpm run dev
    user: "${UID:-1000}:${GID:-1000}"

  syllabus-backend:
    build:
      context: ./syllabus-backend
      dockerfile: Dockerfile.dev
    restart: no
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /workspace
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=syllabus
    command: go run src/cmd/api/main.go
    user: "${UID:-1000}:${GID:-1000}"

  syllabus-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=syllabus

  syllabus-scrape:
    build:
      context: ./syllabus-scrape
      dockerfile: Dockerfile.dev
    restart: no
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: syllabus-scrape-node-modules
        target: /workspace/syllabus-scrape/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - rishu-app_network
    command: sleep infinity
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  frontend-node-modules:
  legacy-frontend-node-modules:
  legacy-syllabus-frontend-node-modules:
  syllabus-scrape-node-modules:
