FROM python:3.12.5-slim-bullseye
ENV PYTHONUNBUFFERD=1

WORKDIR /workspace/backend

COPY ./requirements.txt .
RUN pip install --upgrade pip\
  && pip install --upgrade setuptools\
  && pip install --no-cache-dir -r requirements.txt
