FROM python:3.12.5-slim-bullseye
ENV PYTHONUNBUFFERD=1

WORKDIR /workspace/backend

# 非rootユーザーを作成
RUN groupadd -g 1000 pythongroup && \
  useradd -m -u 1000 -g pythongroup python

# 必要なファイルをコピー
COPY ./requirements.txt .

# ユーザーを切り替え
USER python

# パッケージをインストール
RUN pip install --upgrade pip \
  && pip install --upgrade setuptools \
  && pip install --no-cache-dir -r requirements.txt

