FROM node:20-bullseye-slim

# Chromeと必要なフォント・ライブラリをインストール
RUN apt-get update \
  && apt-get install -y wget gnupg \
  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y \
    google-chrome-stable \
    fonts-ipafont-gothic \
    fonts-wqy-zenhei \
    fonts-thai-tlwg \
    fonts-kacst \
    fonts-freefont-ttf \
    libxss1 \
    --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/syllabus-scrape

COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN mkdir -p /workspace/syllabus-scrape/node_modules && \
  chown -R node:node /workspace && \
  mkdir -p /workspace/syllabus-scrape/.pnpm-store && \
  chown -R node:node /workspace/syllabus-scrape/.pnpm-store && \
  npm install -g pnpm && \
  pnpm config set store-dir /workspace/syllabus-scrape/.pnpm-store

USER node
RUN pnpm install
