FROM node:22-bullseye-slim

WORKDIR /workspace/legacy-syllabus-frontend

# 依存関係をインストール
COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN mkdir -p /workspace/legacy-syllabus-frontend/node_modules && \
  chown -R node:node /workspace && \
  mkdir -p /workspace/legacy-syllabus-frontend/.pnpm-store && \
  chown -R node:node /workspace/legacy-syllabus-frontend/.pnpm-store
RUN npm install -g pnpm

USER node

RUN pnpm config set store-dir /workspace/legacy-syllabus-frontend/.pnpm-store

RUN pnpm install

CMD [ "sleep", "infinity" ]