export const SYLLABUS_SELECTORS = {
  title: "#ctl00_phContents_Detail_lbl_lct_name_double",
  instructors: "#ctl00_phContents_Detail_lbl_syl_staff_name_link_double",
  numbering: "#ctl00_phContents_Detail_lbl_numbering",
  courseNumber: "#ctl00_phContents_Detail_lbl_lct_cd",
  lectureForm: "#ctl00_phContents_Detail_lbl_lct_type_name",
  numberOfProper: "#ctl00_phContents_Detail_lbl_class_size_disp",
  schedule: "#ctl00_phContents_Detail_lbl_day_period",
  classFormat: "#ctl00_phContents_Detail_lbl_format_name_disp",
  subjectDistinguished: "#ctl00_phContents_Detail_lbl_sbj_div_name",
  semester: "#ctl00_phContents_Detail_lbl_lct_term_name",
  numberOfCredits: "#ctl00_phContents_Detail_lbl_credits_disp",
  max60CreditsFlag: "#ctl00_phContents_Detail_lbl_media_name_disp",
  targetStudents: "#ctl00_phContents_Detail_lbl_target",
  keywords: "#ctl00_phContents_Detail_lbl_keyword_disp",
  lectureRoomInfo: "#ctl00_phContents_Detail_lbl_lecture_room_infomation",
  openAccount: "#ctl00_phContents_Detail_lbl_open_account",
  note: "#ctl00_phContents_Detail_lbl_note",
  detail: "#ctl00_phContents_Detail_LctDetail",
  department: "#ctl00_phContents_Detail_lbl_faculty_name",
};
